# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhuangtianyi/Codes/OOP/CornerBlockList

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhuangtianyi/Codes/OOP/CornerBlockList

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhuangtianyi/Codes/OOP/CornerBlockList/CMakeFiles /Users/zhuangtianyi/Codes/OOP/CornerBlockList/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhuangtianyi/Codes/OOP/CornerBlockList/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CornerBlockList

# Build rule for target.
CornerBlockList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CornerBlockList
.PHONY : CornerBlockList

# fast build rule for target.
CornerBlockList/fast:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/build
.PHONY : CornerBlockList/fast

src/CornerBlockList.o: src/CornerBlockList.cpp.o
.PHONY : src/CornerBlockList.o

# target to build an object file
src/CornerBlockList.cpp.o:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/CornerBlockList.cpp.o
.PHONY : src/CornerBlockList.cpp.o

src/CornerBlockList.i: src/CornerBlockList.cpp.i
.PHONY : src/CornerBlockList.i

# target to preprocess a source file
src/CornerBlockList.cpp.i:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/CornerBlockList.cpp.i
.PHONY : src/CornerBlockList.cpp.i

src/CornerBlockList.s: src/CornerBlockList.cpp.s
.PHONY : src/CornerBlockList.s

# target to generate assembly for a file
src/CornerBlockList.cpp.s:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/CornerBlockList.cpp.s
.PHONY : src/CornerBlockList.cpp.s

src/Rectangle.o: src/Rectangle.cpp.o
.PHONY : src/Rectangle.o

# target to build an object file
src/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/Rectangle.cpp.o
.PHONY : src/Rectangle.cpp.o

src/Rectangle.i: src/Rectangle.cpp.i
.PHONY : src/Rectangle.i

# target to preprocess a source file
src/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/Rectangle.cpp.i
.PHONY : src/Rectangle.cpp.i

src/Rectangle.s: src/Rectangle.cpp.s
.PHONY : src/Rectangle.s

# target to generate assembly for a file
src/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/Rectangle.cpp.s
.PHONY : src/Rectangle.cpp.s

src/TestCaseGenerator.o: src/TestCaseGenerator.cpp.o
.PHONY : src/TestCaseGenerator.o

# target to build an object file
src/TestCaseGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/TestCaseGenerator.cpp.o
.PHONY : src/TestCaseGenerator.cpp.o

src/TestCaseGenerator.i: src/TestCaseGenerator.cpp.i
.PHONY : src/TestCaseGenerator.i

# target to preprocess a source file
src/TestCaseGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/TestCaseGenerator.cpp.i
.PHONY : src/TestCaseGenerator.cpp.i

src/TestCaseGenerator.s: src/TestCaseGenerator.cpp.s
.PHONY : src/TestCaseGenerator.s

# target to generate assembly for a file
src/TestCaseGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/TestCaseGenerator.cpp.s
.PHONY : src/TestCaseGenerator.cpp.s

src/Visualizer.o: src/Visualizer.cpp.o
.PHONY : src/Visualizer.o

# target to build an object file
src/Visualizer.cpp.o:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/Visualizer.cpp.o
.PHONY : src/Visualizer.cpp.o

src/Visualizer.i: src/Visualizer.cpp.i
.PHONY : src/Visualizer.i

# target to preprocess a source file
src/Visualizer.cpp.i:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/Visualizer.cpp.i
.PHONY : src/Visualizer.cpp.i

src/Visualizer.s: src/Visualizer.cpp.s
.PHONY : src/Visualizer.s

# target to generate assembly for a file
src/Visualizer.cpp.s:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/Visualizer.cpp.s
.PHONY : src/Visualizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CornerBlockList.dir/build.make CMakeFiles/CornerBlockList.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CornerBlockList"
	@echo "... src/CornerBlockList.o"
	@echo "... src/CornerBlockList.i"
	@echo "... src/CornerBlockList.s"
	@echo "... src/Rectangle.o"
	@echo "... src/Rectangle.i"
	@echo "... src/Rectangle.s"
	@echo "... src/TestCaseGenerator.o"
	@echo "... src/TestCaseGenerator.i"
	@echo "... src/TestCaseGenerator.s"
	@echo "... src/Visualizer.o"
	@echo "... src/Visualizer.i"
	@echo "... src/Visualizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

