//
// Created by ZhuangTianYi on 15/6/21.
//

#ifndef CORNERBLOCKLIST_TESTCASEGENERATOR_H
#define CORNERBLOCKLIST_TESTCASEGENERATOR_H


class TestCaseGenerator {

};


#endif //CORNERBLOCKLIST_TESTCASEGENERATOR_H
